port: 9001
grpc_port: 9005
jwt:
  secret: "QuFsuM4dNSHfsfyjrCQeKAEE4KRj5sQR6Ez4Y6kcCh4XBgzJ43dHSm9mb9Y6kBBfUajgxjAbXRX4FttD"
sqs:
  fake: true
  region: us-west-2
  endpoint: http://localhost:4566
sns:
  fake: true
  region: us-west-2
  endpoint: http://localhost:4566
postgres:
  host: tradew-rds.cbkii6q0lg0j.us-west-2.rds.amazonaws.com
  user: myuser
  password: 123123123
  port: 5432
  database: tradew
events:
  items-updated: items-updated
