port: 9001
grpc_port: 9005
jwt:
  secret: "QuFsuM4dNSHfsfyjrCQeKAEE4KRj5sQR6Ez4Y6kcCh4XBgzJ43dHSm9mb9Y6kBBfUajgxjAbXRX4FttD"
sqs:
  region: us-west2
  endpoint: http://localhost:4566
sns:
  region: us-west2
  endpoint: http://localhost:4566
postgres:
  host: localhost
  user: postgres
  password: admin
  port: 5432
  database: inventory
events:
  items-updated: items-updated
